const namespaces = {
  w: 'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
  m: 'http://schemas.openxmlformats.org/officeDocument/2006/math',
  r: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
  wp: 'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing',
  a: 'http://schemas.openxmlformats.org/drawingml/2006/main',
  ns6: 'http://schemas.openxmlformats.org/schemaLibrary/2006/main',
  c: 'http://schemas.openxmlformats.org/drawingml/2006/chart',
  ns8: 'http://schemas.openxmlformats.org/drawingml/2006/chartDrawing',
  dgm: 'http://schemas.openxmlformats.org/drawingml/2006/diagram',
  pic: 'http://schemas.openxmlformats.org/drawingml/2006/picture',
  ns11: 'http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing',
  dsp: 'http://schemas.microsoft.com/office/drawing/2008/diagram',
  ns13: 'urn:schemas-microsoft-com:office:excel',
  o: 'urn:schemas-microsoft-com:office:office',
  v: 'urn:schemas-microsoft-com:vml',
  w10: 'urn:schemas-microsoft-com:office:word',
  ns17: 'urn:schemas-microsoft-com:office:powerpoint',
  odx: 'http://opendope.org/xpaths',
  odc: 'http://opendope.org/conditions',
  odq: 'http://opendope.org/questions',
  odi: 'http://opendope.org/components',
  odgm: 'http://opendope.org/SmartArt/DataHierarchy',
  ns24: 'http://schemas.openxmlformats.org/officeDocument/2006/bibliography',
  ns25: 'http://schemas.openxmlformats.org/drawingml/2006/compatibility',
  ns26: 'http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas',
};

export default namespaces;
