const namespaces = {
  a: 'http://schemas.openxmlformats.org/drawingml/2006/main',
  b: 'http://purl.oclc.org/ooxml/officeDocument/bibliography',
  cp: 'http://purl.oclc.org/ooxml/drawingml/chartDrawing',
  cdr: 'http://schemas.openxmlformats.org/drawingml/2006/chartDrawing',
  dc: 'http://purl.org/dc/elements/1.1/',
  dcmitype: 'http://purl.org/dc/dcmitype/',
  dcterms: 'http://purl.org/dc/terms/',
  ds: 'http://purl.oclc.org/ooxml/officeDocument/customXml',
  o: 'urn:schemas-microsoft-com:office:office',
  pic: 'http://purl.oclc.org/ooxml/drawingml/picture',
  r: 'http://purl.oclc.org/ooxml/officeDocument/relationships',
  sl: 'http://purl.oclc.org/ooxml/schemaLibrary/main',
  v: 'urn:schemas-microsoft-com:vml',
  ve: 'http://schemas.openxmlformats.org/markup-compatibility/2006',
  vt: 'http://purl.oclc.org/ooxml/officeDocument/docPropsVTypes',
  w: 'http://purl.oclc.org/ooxml/wordprocessingml/main',
  w10: 'urn:schemas-microsoft-com:office:word',
  wp: 'http://purl.oclc.org/ooxml/drawingml/wordprocessingDrawing',
  xsd: 'http://www.w3.org/2001/XMLSchema',
  xsi: 'http://www.w3.org/2001/XMLSchema-instance',
  numbering: 'http://purl.oclc.org/ooxml/officeDocument/relationships/numbering',
  hyperlinks: 'http://purl.oclc.org/ooxml/officeDocument/relationships/hyperlink',
  images: 'http://purl.oclc.org/ooxml/officeDocument/relationships/image',
  styles: 'http://purl.oclc.org/ooxml/officeDocument/relationships/styles',
  headers: 'http://purl.oclc.org/ooxml/officeDocument/relationships/header',
  coreProperties: 'http://schemas.openxmlformats.org/package/2006/metadata/core-properties',
  officeDocument: 'http://purl.oclc.org/ooxml/officeDocument/relationships/officeDocument',
  corePropertiesRelation:
    'http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties',
};

export default namespaces;
